---- INSERT PARA LAS TABLAS---

---- TIPOS DE PLATOS---
INSERT INTO TIPOPLATO VALUES (1, 'Huevos revueltos', 1);
INSERT INTO TIPOPLATO VALUES (2, 'Hojaldra y salchichas guisadas', 1);
INSERT INTO TIPOPLATO VALUES (3, 'Arroz con pollo', 2);
INSERT INTO TIPOPLATO VALUES (4, 'Arroz con salchicha guisada', 3);

-- CATEGORIAS ---
INSERT INTO CATEGORIAS VALUES (1, 'desayuno');	
INSERT INTO CATEGORIAS VALUES (2, 'almuerzo');	
INSERT INTO CATEGORIAS VALUES (3, 'cena');	

-- INGREDIENTES -- 
-- TODO Añadir cambios
INSERT INTO INGREDIENTES VALUES (1, 'aceite de soja');
INSERT INTO INGREDIENTES VALUES (2, 'aceite de maiz');
INSERT INTO INGREDIENTES VALUES (3, 'aceite de oliva');
INSERT INTO INGREDIENTES VALUES (4, 'leche');
INSERT INTO INGREDIENTES VALUES (5, 'queso mozarella');
INSERT INTO INGREDIENTES VALUES (6, 'queso parmesano');
INSERT INTO INGREDIENTES VALUES (7, 'queso prensado');
INSERT INTO INGREDIENTES VALUES (8, 'mantequilla');
INSERT INTO INGREDIENTES VALUES (9, 'leche');
INSERT INTO INGREDIENTES VALUES (10, 'garbanzos');
INSERT INTO INGREDIENTES VALUES (11, 'guisantes');
INSERT INTO INGREDIENTES VALUES (12, 'lentejas');
INSERT INTO INGREDIENTES VALUES (13, 'patatas');
INSERT INTO INGREDIENTES VALUES (14, 'lechuga');
INSERT INTO INGREDIENTES VALUES (15, 'brocoli');
INSERT INTO INGREDIENTES VALUES (16, 'cebolla');
INSERT INTO INGREDIENTES VALUES (17, 'ajo');
INSERT INTO INGREDIENTES VALUES (18, 'tomate');
INSERT INTO INGREDIENTES VALUES (19, 'zanahoria');
INSERT INTO INGREDIENTES VALUES (20, 'espinaca');
INSERT INTO INGREDIENTES VALUES (21, 'maiz');
INSERT INTO INGREDIENTES VALUES (22, 'remolacha');
INSERT INTO INGREDIENTES VALUES (23, 'pepino');
INSERT INTO INGREDIENTES VALUES (24, 'platano verde');
INSERT INTO INGREDIENTES VALUES (25, 'platano maduro');
INSERT INTO INGREDIENTES VALUES (26, 'pimienta');
INSERT INTO INGREDIENTES VALUES (27, 'sal ');
INSERT INTO INGREDIENTES VALUES (28, 'oregano');
INSERT INTO INGREDIENTES VALUES (29, 'azucar');
INSERT INTO INGREDIENTES VALUES (30, 'albahaca');
INSERT INTO INGREDIENTES VALUES (31, 'arroz');
INSERT INTO INGREDIENTES VALUES (32, 'frijoles rojos');
INSERT INTO INGREDIENTES VALUES (33, 'frijoles negros');
INSERT INTO INGREDIENTES VALUES (34, 'jengibre');
INSERT INTO INGREDIENTES VALUES (35, 'yuca');
INSERT INTO INGREDIENTES VALUES (36, 'otoe');
INSERT INTO INGREDIENTES VALUES (37, 'aguacate');
INSERT INTO INGREDIENTES VALUES (38, 'melon');
INSERT INTO INGREDIENTES VALUES (39, 'pina');
INSERT INTO INGREDIENTES VALUES (40, 'sandia');
INSERT INTO INGREDIENTES VALUES (41, 'naranja');
INSERT INTO INGREDIENTES VALUES (42, 'limon');
INSERT INTO INGREDIENTES VALUES (43, 'harina');
INSERT INTO INGREDIENTES VALUES (44, 'pasta');
INSERT INTO INGREDIENTES VALUES (45, 'atun');
INSERT INTO INGREDIENTES VALUES (46, 'sardina');
INSERT INTO INGREDIENTES VALUES (47, 'camaron');
INSERT INTO INGREDIENTES VALUES (48, 'corvina');
INSERT INTO INGREDIENTES VALUES (49, 'salmon');
INSERT INTO INGREDIENTES VALUES (50, 'pollo');
INSERT INTO INGREDIENTES VALUES (51, 'huevos');
INSERT INTO INGREDIENTES VALUES (52, 'agua');
INSERT INTO INGREDIENTES VALUES (53, 'carne de falda');
INSERT INTO INGREDIENTES VALUES (54, 'perejil');
INSERT INTO INGREDIENTES VALUES (55, 'recao');
INSERT INTO INGREDIENTES VALUES (56, 'jalapeno');
INSERT INTO INGREDIENTES VALUES (57, 'salsa inglesa');
INSERT INTO INGREDIENTES VALUES (58, 'salsa de soja');
INSERT INTO INGREDIENTES VALUES (60, 'salsa de tomate');
INSERT INTO INGREDIENTES VALUES (61, 'mayonesa');
INSERT INTO INGREDIENTES VALUES (62, 'mostaza');
INSERT INTO INGREDIENTES VALUES (63, 'aceite vegetal');
INSERT INTO INGREDIENTES VALUES (64, 'alas de pollo');
INSERT INTO INGREDIENTES VALUES (65, 'pechuga de pollo');
INSERT INTO INGREDIENTES VALUES (66, 'pimenton rojo');
INSERT INTO INGREDIENTES VALUES (67, 'pimenton verde');
INSERT INTO INGREDIENTES VALUES (68, 'pimenton amarillo');
INSERT INTO INGREDIENTES VALUES (69, 'pasta de tomate');
INSERT INTO INGREDIENTES VALUES (70, 'vinagre blanco');
INSERT INTO INGREDIENTES VALUES (71, 'salsa china');
INSERT INTO INGREDIENTES VALUES (72, 'aji');
INSERT INTO INGREDIENTES VALUES (73, 'chile serrano');
INSERT INTO INGREDIENTES VALUES (74, 'cilantro');
INSERT INTO INGREDIENTES VALUES (75, 'aceituna');

-- UNIDADES --
-- TODO Añadir Unidades
INSERT INTO UNIDADEMEDIDA VALUES (1, 'libra ');
INSERT INTO UNIDADEMEDIDA VALUES (2, 'kilogramo');
INSERT INTO UNIDADEMEDIDA VALUES (3, 'pizca');
INSERT INTO UNIDADEMEDIDA VALUES (4, 'taza');
INSERT INTO UNIDADEMEDIDA VALUES (5, 'onzas');
INSERT INTO UNIDADEMEDIDA VALUES (6, 'gramos');
INSERT INTO UNIDADEMEDIDA VALUES (7, 'cucharadas');
INSERT INTO UNIDADEMEDIDA VALUES (8, 'grados celcius');
INSERT INTO UNIDADEMEDIDA VALUES (9, 'grados farenhiet');
INSERT INTO UNIDADEMEDIDA VALUES (10, 'Litros');
INSERT INTO UNIDADEMEDIDA VALUES (11, 'Mililitros');
INSERT INTO UNIDADEMEDIDA VALUES (12, 'galon');
INSERT INTO UNIDADEMEDIDA VALUES (13, 'quartos');
INSERT INTO UNIDADEMEDIDA VALUES (14, 'slide');
INSERT INTO UNIDADEMEDIDA VALUES (15, 'unidad');
INSERT INTO UNIDADEMEDIDA VALUES (16, 'diente');

-- RECETAS --


-- CANTIDADES -- 